### ISSUE TITLE
rancher desktop を追加する

### ISSUE THREAD

**Issue by gotokazuki** [gotokazuki/dotfiles#49]
free docker desktop alternative

### 作業

install

```shell
brew install --cask rancher
```

ファイル作成 (mount volume のため)

`~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml`

```yaml
mountType: 9p
mounts:
  - location: "~"
    9p:
      securityModel: mapped-xattr
      cache: "mmap"
```

起動して設定変更

Preferences -> Application (General) -> Administrative Access (Allow to acquire administrative credentials (sudo access))
Preferences -> Application (Behavior) -> Startup (Automatically start at login), Background (Start in the background)
